version: '3.8'
services:

  # zookeeper:
  #   image: confluentinc/cp-zookeeper:7.0.0
  #   hostname: zookeeper
  #   container_name: zookeeper
  #   environment:
  #     ZOOKEEPER_CLIENT_PORT: 2181
  #     ZOOKEEPER_TICK_TIME: 2000

  # broker:
  #   image: confluentinc/cp-kafka:7.0.0
  #   container_name: broker
  #   ports:
  #     - "9092:9092"
  #   depends_on:
  #     - zookeeper
  #   environment:
  #     KAFKA_BROKER_ID: 1
  #     KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
  #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
  #     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
  #     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  #     KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
  #     KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  front_end:
    build:
      context: ./front_end
    ports:
      - "5001:5001"
    container_name: front_end

  users:
    build:
      context: ./users
    ports:
      - "5002:5002"
    container_name: users

  mongo:
    image: mongo
    container_name: mongo_db
    # ports:
    #   - "27017:27017"
    # restart: always

  nginx:
    image: nginx:latest 
    container_name: nginx
    volumes:
      - "./reverse_proxy/nginx.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "5000:5000"