version: '3.9'
services:

  front_end:
    build:
      context: ./front_end
    ports:
      - "5001:5001"
    container_name: front_end
    depends_on:
      - nginx

  user:
    build:
      context: ./users
    ports:
      - "5002:5002"
    container_name: users
    depends_on:
      - nginx
      
  nginx:
    restart: always
    image: nginx:latest 
    container_name: nginx
    volumes:
      - "./reverse_proxy/nginx.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "5000:80"